import "./globals.css";
import Navbar from "./components/Home/Navbar";
import { CartProvider } from "./context/CartContext";
import Footer from "./components/Home/Footer";
// import "./default-responsive.css";

export const metadata = {
  title: "Glamora - Your Fashion Hub",
  description: "Generated by Parth",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="antialiased">
        <CartProvider>
          <Navbar />
          <div className="w-full mx-auto max-w-6xl xl:max-w-7xl 2xl:max-w-screen-2xl px-4 sm:px-6 md:px-8 lg:px-12 xl:px-14 2xl:px-16">
            {children}
          </div>
        </CartProvider>
        <Footer />
      </body>
    </html>
  );
}
